version: "3"

services:
  db-test:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db-test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  redis-cache:
    image: redis
    restart: always
    ports:
      - 6379:6379